[colors.bright]
black = "0x928374"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe3a84e"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xdfbf8e"

[colors.normal]
black = "0x665c54"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe78a4e"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xdfbf8e"

[colors.primary]
background = "0x1d2021"
foreground = "0xdfbf8e"

[cursor]
blink_interval = 250
blink_timeout = 0
thickness = 0.2
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "alacritty-direct"

[font]
size = 22.5

[font.normal]
family = "Hack Nerd Font"
